# Generated by Django 5.0.3 on 2024-04-23 05:45

import django.db.models.deletion
import django_resized.forms
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_plot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campsite",
            fields=[
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("what3words", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "image1",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=85,
                        scale=None,
                        size=[600, 600],
                        upload_to="photos/",
                    ),
                ),
                (
                    "image2",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=85,
                        scale=None,
                        size=[600, 600],
                        upload_to="photos/",
                    ),
                ),
                (
                    "image3",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=85,
                        scale=None,
                        size=[600, 600],
                        upload_to="photos/",
                    ),
                ),
                (
                    "image4",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=85,
                        scale=None,
                        size=[600, 600],
                        upload_to="photos/",
                    ),
                ),
                (
                    "image5",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=85,
                        scale=None,
                        size=[600, 600],
                        upload_to="photos/",
                    ),
                ),
                (
                    "image6",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=85,
                        scale=None,
                        size=[600, 600],
                        upload_to="photos/",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("contacted", models.BooleanField(default=False)),
                ("contact_notes", models.TextField(blank=True, null=True)),
                ("is_member", models.BooleanField(default=False)),
                ("discount", models.BooleanField(default=False)),
                ("num_plots", models.IntegerField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="plot",
            name="campsite",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campsites",
                to="a_plot.campsite",
            ),
        ),
    ]
