# Generated by Django 5.0.3 on 2024-04-23 07:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_plot", "0005_alter_campsite_options_alter_plot_campsite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campsite",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="campsite",
            name="name",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
