# Generated by Django 5.0.3 on 2024-04-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a_plot", "0006_alter_campsite_id_alter_campsite_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campsite",
            name="id",
        ),
    ]
