# Generated by Django 5.0.3 on 2024-04-23 07:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_plot", "0007_remove_campsite_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="campsite",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=100, unique=True
            ),
        ),
    ]
