# Generated by Django 5.0.3 on 2024-04-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a_plot", "0008_campsite_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campsite",
            old_name="id",
            new_name="site_id",
        ),
    ]
