# Generated by Django 5.0.3 on 2024-03-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="campermode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Hammock", "Hammock"),
                    ("Small Tent", "Small Tent"),
                    ("Large Tent", "Large tent"),
                    ("Car", "Car"),
                    ("Van", "Van"),
                    ("CamperVan", "CamperVan"),
                    ("Motorhome", "Motorhome"),
                    ("Small Caravan", "Small Caravan"),
                    ("Large Caravan", "Large Caravan"),
                    ("Trailer Tent", "Trailer Tent"),
                    ("Cabin/Mobile Home", "Cabin/Mobile Home"),
                    ("Under the Stars", "Under the Stars"),
                ],
                default="Hammock",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="camperstory",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="fav_campsite",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SC_Founder1", "SuperCamper Founder1"),
                    ("SC_Founder2", "SuperCamper Founder2"),
                    ("New_SuperCamper", "New SuperCamper"),
                    ("SuperCamper", "SuperCamper"),
                    ("SuperCamper Expert", "SuperCamper Expert"),
                    ("SuperCamper Master", "SuperCamper Master"),
                    ("Restricted SuperCamper", "Restricted SuperCamper"),
                    ("Banned", "Banned"),
                ],
                default="New SuperCamper",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="nationality",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="numplots",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="plot_reports",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="realname",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
