# Generated by Django 5.0.3 on 2024-04-06 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_users", "0004_profile_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="created",
        ),
    ]
