# Generated by Django 5.0.3 on 2024-04-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a_users", "0003_profile_created"),
        ("a_users", "0006_profile_created"),
    ]

    operations = []
